# main configuration file
session: PSGI

charset: "UTF-8"
template: template_toolkit
layout: main

engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    ENCODING: "UTF-8"
    PRIVATE: 1
    TRIM: 1
    EVAL_PERL: 0
    ANYCASE: "no"
